### ISSUE TITLE
Migrate from Markdown to Asciidoctor

### ISSUE THREAD

**Issue by nfrankel** [Boburmirzo/apisix-workshop#1]

**Comment by Boburmirzo** [comment]
@nfrankel 

Let's discuss first in which format we want to develop the content and share to the audience. 

For me .md format works, but also we can just create it in Lark and publish it simply in pdf and put it into the repo. 

Is there any reason why we want to convert it to  .Asciidoctor?

**Comment by nfrankel** [comment]
>For me .md format works

The biggest issue is that you need to manually reference code from your Markdown file.

>Is there any reason why we want to convert it to .Asciidoctor?

Asciidoctor embeds this feature natively.

>but also we can just create it in Lark and publish it simply in pdf and put it into the repo

Why? Shouldn't GitHub be the single source of truth, with versioning on top?

**Comment by Boburmirzo** [comment]
> The biggest issue is that you need to manually reference code from your Markdown file.

Okay, but it should not be a big issue. 

> Asciidoctor embeds this feature natively.

To me .Asciidoctor is a sort of old tool.  I am okay to develop lab instruction with it unless we do have other options. 
Instead of writing it first in Markdown and converting after. Which tool do you use to develop the content with Asciidoctor? 
I can also use directly Asciidoctor.

> Why? Shouldn't GitHub be the single source of truth, with versioning on top?

Github is okay, I just brought an example. I would also try something new like Gitbook website view content with Github integration. What do you think?

**Comment by nfrankel** [comment]
>Okay, but it should not be a big issue

It is, if you need to keep the documentation and the code in sync manually. Of course, if you commit to do it manually, then I'm fine 😉

>To me .Asciidoctor is a sort of old tool

I don't care whether it's old or not. I care if it does what I need.

>Which tool do you use to develop the content with Asciidoctor?

Regular text editor

>I would also try something new like Gitbook website view content with Github integration

If you can achieve something like [this](https://formations.github.io/java-advanced/tp/streams.html), sure.

**Comment by Boburmirzo** [comment]
> If you can achieve something like [this](https://formations.github.io/java-advanced/tp/streams.html), sure.

We can achieve something like this (But it references only .md files) in the Github repo https://github.com/Boburmirzo/gitbook-example.

https://livermore-1.gitbook.io/untitled/

Or we can also use a special template for this type of instruction. What do you think?

> Regular text editor

It seems there is a plugin for IDEA

https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/quick-start.html

**Comment by Boburmirzo** [comment]
I am closing this issue since md converted to Asciidoctor.
